backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Actus"
    files:
      - name: "posts"
        label: "Publications"
        file: "content/posts.json"
        fields:
          - name: "posts"
            label: "Publications"
            widget: "list"
            label_singular: "Publication"
            summary: "{{title}} — {{date}}"
            fields:
              - { name: "title", label: "Titre", widget: "string" }
              - { name: "body", label: "Corps", widget: "text" }
              - { name: "date", label: "Date", widget: "datetime" }
